-- AlterTable
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "secondary_email" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "birth_date" DATE;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "birth_place" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "marital_status" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "children_count" INTEGER;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "education" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "languages" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "hobbies" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "sports" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "emergency_phone" TEXT;
